### PR TITLE
Install KituraKit pod from repo

### PR DESCRIPTION
**Pull request by alexwishart**
Now able to install KituraKit pod from 'pod' branch of the repo, so can remove a number of steps to simplify the tutorial.

### CODE REVIEW

**Comment by seabaylea** [comment]
Hi Alex. Can you update to resolve the merge conflict?

**Comment by alexwishart** [comment]
@seabaylea I've resolved the conflicts in the latest commit, but it's still saying for me here that there's conflicts to resolve - is it showing the same on your end or are you able to merge?

**Comment by seabaylea** [comment]
Still got a merge conflict I'm afraid.

**Comment by alexwishart** [comment]
@seabaylea no idea why the first merge commit didn't work, but should be ready now 🙂

**Comment by seabaylea** [comment]
LGTM. Merging.

**Pull request merged**
