### PR TITLE
Add Persistence Tutorial

### PR DESCRIPTION
**Pull request by Andrew-Lees11**
This pull request removes the festive changes and adds a readme describing how to add persistence to the Foodtracker. It also contains references to the branch completed backend which is also submitted as a pull request so should be merged together.

### CODE REVIEW

**Comment by helenmasters** [comment]
A few review comments - 

- [ ] Within README.md "Apon completion of this tutorial"  should be Upon completion...

- [ ] We need to standardise our terminology. You've created within the README.md "Adding a Database to FoodTracker Server with Swift-Kuery" to next steps but in other references within the next steps we refer to Kitura FoodServer or just FoodServer. We need to stick with one of these, either 'FoodTracker Server' or 'Kitura FoodServer' (which I'm happy to be shortened to FoodServer later on) or users will get confused.  I think the new title should be 'Add a Database to the Kitura FoodServer with Swift-Query'. 

- This then needs changing in this README.md where we reference this in the next steps sections at the top and bottom of the README.md. This will also need to be the new title in AddDatabase.md.

- [ ] In README.md please change "This meals that if the server is restated all the saved data will be lost." to "This means that if the server is restarted the saved data will be lost."

- [ ] In README.md please change "These following tutorial demonstrates how to add a PostgreSQL database to the FoodTracker server using Swift-Kuery and Swift-Kuery-PostgreSQL to add data persistence to the server." to "The following steps describe how to 'Add a Database to the Kitura FoodServer with Swift-Query'(this last bit of text needs to be a link)".

**Comment by helenmasters** [comment]
Comments on AddDatabase.md:

- [ ] A minor comment but I don't like the fact that the top of the file has almost complete repetition between "This tutorial builds upon a server and application created by following the FoodTrackerBackend tutorial." and "This tutorial follows on from the FoodTracker Application and server created by following the FoodTrackerBackend tutorial."

We could change this to something like:
"Now that there is a 'FoodServer as a backend for the FoodTracker app' (link to FoodTrackerBackend tutorial), you can add a database so that Meal data persists between server restarts.
 
The steps below demonstrate how to add a PostgreSQL database to the Kitura FoodServer using Swift-Kuery and Swift-Kuery-PostgreSQL."

- [ ] FoodTracker Application and server - why does the Application have a capital A I can't see why it should?

- [ ] Within Creating a PostgreSQL Database please can we use a lower case 'S' for Server

- [ ] Within Adding Swift-Kuery dependencies to your server again we have a a capital 'S' for Server, please make it lowercase. I think we should have backticks around the package.swift reference in this section too.

- [ ] "Inside the loadHander function create an select query." should be "Inside the loadHandler function create a select query."

- [ ]"On the line below your temporary Meal store, Iterate through the rows returned by the database." I think the Iterate through the rows returned by the database should be written first, but if you want it this way round make the Iterate have a lower case i

- [ ] "This installation should have installed two applications we need, namely createdb and psql,..." shouldn't createdb and psql have backticks around them?

- [ ] At the end of this file I think we should change the wording around, ie why you should look at PersistentiOSKituraKit should be listed first - something like -
"In this tutorial we used GET and POST calls, for further examples of RESTful HTTP and SQL calls please see PersistentiOSKituraKit which contains a complete ToDo List application with database persistence."

"If you would like to view a complete ToDoList application with database persistence, which contains further examples of HTTP and SQL calls please see PersistentiOSKituraKit."

**Comment by helenmasters** [comment]
Within the file https://github.com/IBM-Swift/iOSSampleKituraKit/blob/persistentiOSKituraKit/ToDoServer/Sources/Application/Application.swift the comment lines for the functions are unreadable in git because they are so long, e.g.
    /**
     The createHandler function tells the server how to handle an HTTP POST request. It receives a ToDo object from the client and adds an unique identify and URL. The values from the ToDo object are then inserted into the mySQL database using SwiftKuery and SwiftKueryMySQL. It will return either, a ToDo object, with the RequestError being nil, or a RequestError, with the ToDo object being nil.
     */

**Comment by Andrew-Lees11** [comment]
Ok these have been updated on the pull requests

**Comment by seabaylea** [comment]
LGTM. Merging.

**Pull request merged**
